### ISSUE TITLE
Compilation fails in the build step

### ISSUE THREAD

**Issue by tferi** [mikeyhu/scaladiagrams#4]
Here's the error output:

```
[info] Loading global plugins from /Users/tothferenc/.sbt/0.13/plugins
[info] Loading project definition from /Users/tothferenc/scaladiagrams/project
[info] Set current project to scaladiagrams (in build file:/Users/tothferenc/scaladiagrams/)
[info] Compiling 4 Scala sources to /Users/tothferenc/scaladiagrams/target/scala-2.9.2/classes...
[error] error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[error] (bad constant pool tag 18 at byte 10)
[error] error while loading AnnotatedElement, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
[error] (bad constant pool tag 18 at byte 76)
[error] /Users/tothferenc/scaladiagrams/src/main/scala/net/invalidkeyword/scaladiagrams/ScalaSourceParser.scala:64: overloaded method value parseAll with alternatives:
[error]   [T](p: RunParser.this.Parser[T], in: java.lang.CharSequence)RunParser.this.ParseResult[T] <and>
[error]   [T](p: RunParser.this.Parser[T], in: java.io.Reader)RunParser.this.ParseResult[T] <and>
[error]   [T](p: RunParser.this.Parser[T], in: scala.util.parsing.input.Reader[Char])RunParser.this.ParseResult[T]
[error]  cannot be applied to (RunParser.this.Parser[RunParser.this.RootType], String)
[error]   def run(in: String): ParseResult[RootType] = parseAll(root, in)
[error]                                                ^
[error] three errors found
[error] (compile:compile) Compilation failed
[error] Total time: 4 s, completed Mar 23, 2015 7:07:11 PM
```

What could the problem be?

**Comment by mikeyhu** [comment]
ScalaDiagrams is currently using Scala 2.9 and sbt 0.13.7; neither of these play nicely with Java 1.8. The best thing to do is to use Java 1.7 for now.

I will look at updating the dependencies as soon as I have time.

**Comment by tferi** [comment]
Thank you!

**Comment by dbYoung** [comment]
1. install openjdk7
2. change default java version openjdk7
`/usr/sbin/alternatives --config java`
3. sudo ./build

it will work.

**Comment by JamesSullivan** [comment]
I've put in a pull request that will work with Java 1.8 and Scala 2.11.

**Comment by mikeyhu** [comment]
@JamesSullivan thanks for doing this; I've merged it in and will close the issue.
